
name: Deploy Vite Site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Grants permission to push to the repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Disable default credentials

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        
      - name: Generate blog data
        run: node src/apps/blog/scripts/build.js

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          npx gh-pages -d dist -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/MilanPecov/devfolio-galaxy.git
